version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login --username="$(docker run ktruckenmiller/credstash credstash get dockercloud.username)" --password="$(docker run ktruckenmiller/credstash credstash get dockercloud.password)"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -f Dockerfile.ruby -t docker-friend:$IMAGE_TAG .
      - docker build -f Dockerfile.node -t docker-events:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push docker-friend:$IMAGE_TAG
      - docker push docker-events:$IMAGE_TAG
