version: '2'
services:
  dockerfriend:
    container_name: docker-friend
    depends_on:
      - events
    image: ktruckenmiller/docker-friend
    volumes:
      - ~/.aws:/root/.aws:ro
    volumes_from:
      - events
    ports:
      - 8010:9292
    restart: always

  events:
    container_name: docker-events
    image: ktruckenmiller/docker-events
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    restart: always
